Repository smg-automotive/components-pkg, pull requests merged in 2024-12, with the labels that each got.

#1232 feat: add video camera icon
  src/components/icons/VideoCameraIcon.tsx
  src/components/icons/index.ts
Labels: released on @dbojovic-vsst-3051-about-us

#1221 feat(change-email-link): activate for all users and update paths
  src/components/navigation/header/config/DrawerNodeItems.tsx
Labels: released on @lkappeler-SST-1067-change-email-links

#1238 fix: popover component
  src/components/popover/index.tsx
Labels: released on @ST-444

#1242 fix: add zIndex popover props
  src/components/filterPatterns/popover/Popover.tsx
  src/components/filterPatterns/popover/index.tsx
  src/components/filterPatterns/popover/props.ts
  src/components/popover/index.tsx
Labels: released on @popover-insights

#1244 fix: update link for sellers search
  src/components/navigation/footer/config/index.ts
  src/components/navigation/header/config/DrawerNodeItems.tsx
Labels: released on @fix-sellers-search-link
