Repository smg-automotive/components-pkg, pull requests merged in 2025-07, with the labels that each got.

#1438 fix: popover white space
  src/components/popover/index.tsx
Labels: released on @ST-1149-bug-popover

#1455 Merge 23.x
  Dockerfile
  package-lock.json
  package.json
  src/components/icons/CollapseIcon.tsx
  src/components/icons/ExpandIcon.tsx
  src/components/icons/OverflowVerticalIcon.tsx
  src/components/icons/index.ts
  src/components/navigation/footer/config/index.ts
  src/components/navigation/header/config/DrawerNodeItems.tsx
  src/components/navigation/header/config/user.ts
  src/components/popover/index.tsx
  src/locales/de/dict.json
  src/locales/en/dict.json
  src/locales/fr/dict.json
  src/locales/it/dict.json
Labels: released on @merge-23.x

#1458 feat: Align lanauge settings
  src/components/navigation/header/config/DrawerNodeItems.tsx
  src/components/navigation/header/config/user.ts
Labels: released on @lkappeler-language-selection

#1469 fix: remove c2b feature flag
  src/components/navigation/footer/config/index.ts
  src/components/navigation/footer/index.tsx
Labels: released on @fix-remove-c2b-feature-flag

#1472 fix: install reverted i18n version
  package-lock.json
  package.json
Labels: released on @lkappeler-fix-rosetta

#1474 Update main branch
  package-lock.json
  package.json
Labels: released on @lkappeler-resolve-main-conflicts

#1465 fix: seller management links
  src/components/navigation/header/config/Presence.tsx
Labels: released on @fix-seller-management-links

#1468 fix: price estimator link
  src/components/navigation/header/config/estimate.ts
Labels: released on @ST-1207

#1480 fix(temp): Conditionally hide tenant selection header menu
  src/components/navigation/header/__tests__/index.Test.tsx
  src/components/navigation/header/index.stories.tsx
  src/components/navigation/header/index.tsx
Labels: released on @conditionally-hide-tenant-selection

#1477 feat: accordion migration to v3
  src-v2/components/accordion/AccordionButton.tsx
  src-v2/components/accordion/AccordionIcon.tsx
  src-v2/components/accordion/AccordionItem.tsx
  src-v2/components/accordion/AccordionPanel.tsx
  src-v2/components/accordion/index.tsx
  src-v2/components/index.ts
  src-v2/hooks/index.ts
  src-v2/hooks/useAccordionItemState.ts
  src/components/accordion/AccordionButton.tsx
  src/components/accordion/AccordionItem.tsx
  src/components/accordion/AccordionPanel.tsx
  src/components/accordion/__tests__/Accordion.Test.tsx
  src/components/accordion/index.stories.tsx
  src/components/accordion/index.tsx
  src/components/index.ts
  src/themes/shared/keyframes.ts
  src/themes/shared/slotRecipes/accordion.ts
Labels: released on @feat-ST-1260-accordion-migration

#1498 feat: swap logout links on error page
  src/components/errorPage/actions/primary/BackToLogin.tsx
Labels: released on @lkappeler-FED-557-switch-logout-links
